graph TB
subgraph "Greg Anthony (RBO  = 0.39)"
c1["Williams, Monty (PHX)"]-.->c2["Snyder, Quin (UTA)"]-.->c3["Rivers, Doc (PHI)"]
end
subgraph "Bill Simmons (RBO = 0.6)"
a1["Williams, Monty (PHX)"]-.->a2["Thibodeau, Tom (NYK)"]-.->a3["Nash, Steve (BKN)"]
end
subgraph "Final Result (RBO = 1)"
b1["Thibodeau, Tom (NYK)"]-.->b2["Williams, Monty (PHX)"]-.->b3["Snyder, Quin (UTA)"]
end